# Site settings
title: Grant Staublin
email: grant@grantstaublin.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
# baseurl: "http://gcstaublin.github.io"
baseurl: ''
# url: "http://grantstaublin.com"
url: "http://localhost:4000"

# Build settings
markdown: kramdown
permalink: /articles/:title
paginate: 2
paginate_path: "archive/page/:num"




exclude: [
  .git,
  .gitignore,
  .DS_Store,
  # CNAME,
  static/svg,
  static/scss,
  .sass-cache,
  package.json,
  Gruntfile.js,
  node_modules,
  bower.json,
  tasks,
  readme.md
]
